In [2]:
1.1

import numpy as np
n = int(input())
z = np.zeros((1, n))
print(z)

5
[[0. 0. 0. 0. 0.]]


1.2. Посчитайте размер матрицы Z в байтах и выведите его на печать. Чтобы узнать размер (в байтах) 1 элемента матрицы используйте
атрибут https://docs.scipy.org/doc/numpy1.15.1/reference/generated/numpy.ndarray.itemsize.html

In [3]:
import numpy as np

a = np.zeros((10,10))
print(a.size * a.itemsize)
b = np.array([1,2,3], dtype=np.float64)
print(b.size * b.itemsize)

800
24


1.3. Считайте 2 числа:
 n - размер Numpy вектора
 x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора
должны быть равны 0. Сохраните вектор в переменную Z.

In [10]:
import numpy as np

n = int(input("n = "))
x = int(input("x = "))
z = np.zeros(n)
z[x]=1
print(z)

n= 10
x= 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


1.4. Считайте 2 числа n, m. Создайте вектор Z состоящий из чисел от n до m с шагом 1.

In [11]:
import numpy as np

n = int(input("n = "))
m = int(input("m = "))
if n>m:
  z = np.arange(n, m-1, -1)
else:
  z = np.arange(n, m+1, 1)
print(z)

n = 10
m = 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


1.5. Дан вектор Z. "Разверните" его.

In [13]:
import numpy as np

z = np.array([1, 2, 3, 4])
z = z[::-1]
print(z)

[4 3 2 1]


1.6. Считайте 3 числа:

 n - количество элементов матрицы

 m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).

Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.

In [17]:
import numpy as np

n = int(input(" "))
m, k = map(int, input().split())
z = np.arange(n).reshape(m,k)

print(z)

 6
2 3
[[0 1 2]
 [3 4 5]]


1.7. Дан вектор Z. Запишите в переменную NonZerros индексы ненулевых элементов.
Используйте
функцию https://docs.scipy.org/doc/numpy1.15.0/reference/generated/numpy.nonzero.html

In [18]:
import numpy as np

z = np.array([1, 0, 2, 0, 3, 0, 4])
n = np.nonzero(z)
print(n)

(array([0, 2, 4, 6]),)


1.8. Считайте число n. Создайте единичную матрицу размера n, сохраните результат в переменную Z.

In [19]:
import numpy as np

n = int(input(" "))
z = np.eye(n)
print(z)

 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.9 Считайте 3 числа: n, m, l.. Зафиксируйте значение генератора случайных чисел Numpy с помощью numpy.random.seed(42) . Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и сохраните результат в переменную Z.

In [21]:
import numpy as np

np.random.seed(42)
n, m, l = map(int, input().split())
z = np.random.sample(n*(m,l))
print(z)


2 2 2
[[[[0.37454012 0.95071431]
   [0.73199394 0.59865848]]

  [[0.15601864 0.15599452]
   [0.05808361 0.86617615]]]


 [[[0.60111501 0.70807258]
   [0.02058449 0.96990985]]

  [[0.83244264 0.21233911]
   [0.18182497 0.18340451]]]]


 1.10. Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с помощью   . Создайте матрицу n*m из случайных чисел (от 0 до 1).
numpy.random.seed(42)
4
Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).

In [22]:
import numpy as np

n, m = map(int, input().split())
np.random.seed(42)
z = np.random.sample((n,m))
print(z.min())
print(z.max())

10 10
0.005522117123602399
0.9868869366005173


1.11. Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с помощью numpy.random.seed(42).Создайте матрицу n*m из случайных чисел (от 0 до 1). Выведите на печать значение среднего для всей матрицы.

In [23]:
import numpy as np

n, m = map(int, input().split())
np.random.seed(42)
z = np.random.sample((n,m))
print(z.sum()/z.size)

30 30
0.4923750160905882


1.12. Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и сохраните в переменную Z.
A и B могут содержать как int, так и float.

In [24]:
import numpy as np

A = np.array([1.5, 2.5, 3.5]) 
B = np.array([4, 5, 6])
z = np.zeros(A.size)

for i in range(A.size):
  z[i] = A[i] * B[i]
  
print(z.sum())

39.5


1.13. Даны 2 матрицы: A и B. Найдите произведение матриц и сохраните его в переменную Z. Если найти произведение матриц невозможно, то запишите в Z строку:

In [ ]:
import numpy as np


1.14. Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.

In [29]:
import numpy as np

z = np.arange(11)
for i in range(z.size):
  if z[i] > 3 and z[i] < 9:
    z[i] = z[i] * -1
  else:
    pass
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


1.15.Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы. Для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [30]:
import numpy as np
X = np.array([[1, 0, 1],[2, 0, 2],[3, 0, 3],[4, 4, 4]])
count = 1
for i in range(min(X.shape)):
  if X[i,i] == 0:
    pass
  else:
    c = count*X[i,i]
print(c)

3


?

1.16. Считайте число n. Создайте в переменной Z Numpy вектор из нулей длины n.

In [ ]:
1.1

import numpy as np
n = int(input())
z = np.zeros((1, n))
print(z)

1.17. Посчитайте размер матрицы Z в байтах и выведите его на печать. Чтобы узнать размер (в байтах) 1 элемента матрицы используйте
атрибут https://docs.scipy.org/doc/numpy1.15.1/reference/generated/numpy.ndarray.itemsize.html

In [ ]:
import numpy as np

a = np.zeros((10,10))
print(a.size * a.itemsize)
b = np.array([1,2,3], dtype=np.float64)
print(b.size * b.itemsize)

1.18. Считайте 2 числа:
 n - размер Numpy вектора
 x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора
должны быть равны 0. Сохраните вектор в переменную Z.

In [ ]:
import numpy as np

n = int(input("n = "))
x = int(input("x = "))
z = np.zeros(n)
z[x]=1
print(z)

1.19. Считайте 2 числа n, m. Создайте вектор Z состоящий из чисел от n до m с шагом 1.

In [ ]:
import numpy as np

n = int(input("n = "))
m = int(input("m = "))
if n>m:
  z = np.arange(n, m-1, -1)
else:
  z = np.arange(n, m+1, 1)
print(z)

1.20. Дан вектор Z. "Разверните" его.

In [ ]:
import numpy as np

z = np.array([1, 2, 3, 4])
z = z[::-1]
print(z)

1.21. Считайте 3 числа:
 n - количество элементов матрицы
 m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).
Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.

In [ ]:
import numpy as np

n = int(input(" "))
m, k = map(int, input().split())
z = np.arange(n).reshape(m,k)

print(z)

1.22. Дан вектор Z. Запишите в переменную NonZerros индексы ненулевых элементов.
Используйте
функцию https://docs.scipy.org/doc/numpy1.15.0/reference/generated/numpy.nonzero.html Примечание. В этой задаче не нужно ничего считывать или выводить на печать. Матрица Z уже готова, просто создайте NonZerros.

In [ ]:
import numpy as np

z = np.array([1, 0, 2, 0, 3, 0, 4])
n = np.nonzero(z)
print(n)

1.23. Считайте число n. Создайте единичную матрицу размера n, сохраните результат в переменную Z.

In [ ]:
import numpy as np

n = int(input(" "))
z = np.eye(n)
print(z)

1.24. Считайте 3 числа: n, m, l.. Зафиксируйте значение генератора случайных чисел Numpy с помощью numpy.random.seed(42) . Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и сохраните результат в переменную Z.

In [ ]:
import numpy as np

np.random.seed(42)
n, m, l = map(int, input().split())
z = np.random.sample(n*(m,l))
print(z)


1.25. Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с помощью numpy.random.seed(42). Создайте матрицу n*m из случайных чисел (от 0 до 1). Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).

In [ ]:
import numpy as np

n, m = map(int, input().split())
np.random.seed(42)
z = np.random.sample((n,m))
print(z.min())
print(z.max())